import type { ExhibitionEntry, JournalEntry, SeriesEntry } from "@/types/content";

export const fallbackSeries = [
  {
    slug: "raw-matter",
    title: "Raw Matter",
    years: "2024 — 2026",
    statement: "Matter remembers every gesture.",
    description: "Raw Matter studies paint as a physical event: weight, fracture and resistance held in a single surface. The works move between controlled construction and instinctive interruption.",
    cover: { src: "/artworks/untitled-028.png", alt: "Raw Matter, abstract painting in ivory and graphite", position: "48% 48%" },
    artworkSlugs: ["untitled-028", "untitled-027", "untitled-032"],
  },
  {
    slug: "inner-landscapes",
    title: "Inner Landscapes",
    years: "2023 — 2024",
    statement: "The landscape begins where the visible ends.",
    description: "A continuous exploration of the space between the visible and the invisible. Dense fields, ruptures and traces become territories of memory rather than depictions of a place.",
    cover: { src: "/artworks/inner-landscapes.png", alt: "Inner Landscapes, dark abstract painting with a rust gesture", position: "62% 50%" },
    artworkSlugs: ["untitled-032", "untitled-026", "untitled-025", "untitled-024"],
  },
  {
    slug: "fragments",
    title: "Fragments",
    years: "2022 — 2023",
    statement: "A fragment can contain the memory of the whole.",
    description: "Painted fragments gather like incomplete recollections. Their edges remain open, allowing absence and material to shape each other.",
    cover: { src: "/artworks/untitled-032.png", alt: "Fragments series, textured abstract painting", position: "38% 58%" },
    artworkSlugs: ["untitled-027", "untitled-024", "untitled-028"],
  },
  {
    slug: "states-of-silence",
    title: "States of Silence",
    years: "2021 — 2022",
    statement: "Silence is not empty; it is compressed attention.",
    description: "A restrained body of work built from pale grounds, interrupted lines and suspended forms. Silence becomes a material with its own pressure and duration.",
    cover: { src: "/artworks/untitled-028.png", alt: "States of Silence, pale abstract composition", position: "72% 42%" },
    artworkSlugs: ["untitled-025", "untitled-028", "untitled-026"],
  },
] satisfies readonly SeriesEntry[];

export const fallbackExhibitions = [
  {
    slug: "inner-landscapes-almaty",
    title: "Inner Landscapes",
    year: "2026",
    dates: "14 September — 24 November 2026",
    venue: "Aspan Gallery",
    city: "Almaty",
    country: "Kazakhstan",
    format: "Solo exhibition",
    introduction: "A spatial study of interior territories, gathering recent large-scale paintings from the Inner Landscapes cycle.",
    description: "The exhibition is conceived as a gradual movement from shadow toward an open, mineral light. Paintings are installed as thresholds rather than isolated objects, inviting the viewer to move between dense surfaces and moments of silence.",
    image: { src: "/exhibitions/inner-landscapes-installation-placeholder.png", alt: "Inner Landscapes installation view — temporary visual", position: "50% 50%" },
    artworkSlugs: ["untitled-032", "untitled-026", "untitled-025"],
  },
  {
    slug: "states-of-matter-dubai",
    title: "States of Matter",
    year: "2025",
    dates: "6 March — 18 April 2025",
    venue: "Foundry Downtown",
    city: "Dubai",
    country: "UAE",
    format: "Group exhibition",
    introduction: "An exhibition on material intelligence and the changing physical language of contemporary painting.",
    description: "Works from Raw Matter enter a conversation with sculpture and installation. Surface is treated as evidence: scraped, accumulated and rebuilt through time.",
    image: { src: "/exhibitions/inner-landscapes-installation-placeholder.png", alt: "States of Matter installation view — temporary visual", position: "24% 50%" },
    artworkSlugs: ["untitled-028", "untitled-027"],
  },
  {
    slug: "fragments-milan",
    title: "Fragments",
    year: "2024",
    dates: "21 May — 30 June 2024",
    venue: "Spazio Orlandi",
    city: "Milan",
    country: "Italy",
    format: "Solo exhibition",
    introduction: "Paintings and works on paper assembled as an archive of incomplete memory.",
    description: "The installation draws attention to intervals between works. Each fragment carries a different tempo, yet together they form a single field of perception.",
    image: { src: "/exhibitions/inner-landscapes-installation-placeholder.png", alt: "Fragments installation view — temporary visual", position: "76% 50%" },
    artworkSlugs: ["untitled-027", "untitled-024", "untitled-028"],
  },
  {
    slug: "beyond-the-form-new-york",
    title: "Beyond the Form",
    year: "2023",
    dates: "9 November — 17 December 2023",
    venue: "Project Room 11",
    city: "New York",
    country: "USA",
    format: "Group exhibition",
    introduction: "A dialogue between abstraction, memory and the architecture of the image.",
    description: "Selected works trace the point at which recognisable structure gives way to sensation. The exhibition brings together practices rooted in gesture and material transformation.",
    image: { src: "/artworks/untitled-032.png", alt: "Beyond the Form featured painting", position: "50% 48%" },
    artworkSlugs: ["untitled-032", "untitled-025"],
  },
  {
    slug: "silent-structures-berlin",
    title: "Silent Structures",
    year: "2022",
    dates: "12 February — 27 March 2022",
    venue: "Nord Raum",
    city: "Berlin",
    country: "Germany",
    format: "Group exhibition",
    introduction: "Five positions examining silence as an active structural force.",
    description: "The presentation focused on restraint, repetition and the spatial pressure of reduced forms.",
    image: { src: "/artworks/untitled-028.png", alt: "Silent Structures featured painting", position: "56% 60%" },
    artworkSlugs: ["untitled-025", "untitled-028"],
  },
] satisfies readonly ExhibitionEntry[];

export const fallbackJournal = [
  {
    slug: "painting-as-a-threshold",
    title: "Painting as a Threshold",
    category: "Essay",
    date: "18 August 2026",
    excerpt: "On the moment a surface stops being an image and begins to act as a space.",
    body: [
      "I do not begin with an image. I begin with a pressure — something not yet visible, but already present enough to demand a material form.",
      "Every layer is both an assertion and an erasure. Paint accumulates history while scraping opens a path through it. The work becomes a threshold when these opposing movements can remain unresolved.",
      "Abstraction, for me, is not distance from reality. It is a way to approach the part of reality that cannot be fixed by a name.",
    ],
    image: { src: "/artworks/untitled-032.png", alt: "Detail of a layered abstract painting", position: "64% 52%" },
  },
  {
    slug: "notes-from-the-studio-01",
    title: "Notes from the Studio — 01",
    category: "Studio note",
    date: "2 June 2026",
    excerpt: "Light, mineral grounds and the productive resistance of a nearly finished canvas.",
    body: [
      "Morning light changes the painting before I touch it. Areas that felt closed the night before become permeable; marks I considered decisive become provisional.",
      "The studio is a place for attention rather than certainty. A work stays alive while it can still refuse the intention imposed upon it.",
    ],
    image: { src: "/studio/artist-studio-placeholder.png", alt: "Artist studio — temporary editorial visual", position: "50% 48%" },
  },
  {
    slug: "in-conversation-material-memory",
    title: "Material / Memory",
    category: "Conversation",
    date: "11 February 2026",
    excerpt: "A conversation about rhythm, intuition and why the final layer is often the quietest.",
    body: [
      "The work is never a transcription of memory. It is closer to what memory does: it compresses, edits and returns with a changed texture.",
      "Rhythm appears through repetition, but also through interruption. I am interested in the instant a repeated act stops behaving predictably.",
    ],
    image: { src: "/artworks/inner-landscapes.png", alt: "Abstract painting with dark field and red gesture", position: "68% 52%" },
  },
] satisfies readonly JournalEntry[];

export const aboutContent = {
  quote: "Abstraction is not a departure from reality, but a way to be closer to the real.",
  biography: [
    "Alexander Mikhaleff is a contemporary artist whose practice explores the space between visible form and inner perception.",
    "Working primarily with painting and mixed media, he builds surfaces through accumulation, abrasion and repeated gesture. Each work develops slowly, holding traces of decisions that remain visible beneath the final layer.",
    "His practice moves between private studio research and site-responsive exhibition projects across Europe, Central Asia and the Middle East.",
  ],
  statement: [
    "My work begins before the image. It begins with a physical intuition — a density, a silence, a rhythm that has not yet found its structure.",
    "I treat the canvas as a field of memory. Pigment is applied, removed and rebuilt until the work no longer illustrates an idea but carries its own presence.",
  ],
  cv: [
    ["2026", "Inner Landscapes — Aspan Gallery, Almaty"],
    ["2025", "States of Matter — Foundry Downtown, Dubai"],
    ["2024", "Fragments — Spazio Orlandi, Milan"],
    ["2023", "Beyond the Form — Project Room 11, New York"],
    ["2022", "Silent Structures — Nord Raum, Berlin"],
  ],
  press: [
    ["Art Territory", "The material life of abstraction", "2026"],
    ["Surface Journal", "Inside Alexander Mikhaleff’s studio", "2025"],
    ["Contemporary Review", "Painting after the image", "2024"],
  ],
};
