import { defineArrayMember, defineField, defineType } from "sanity";
import { BulkImageArrayInput } from "../components/BulkImageArrayInput";

export const artwork = defineType({
  name: "artwork", title: "Artwork", type: "document",
  groups: [
    { name: "identity", title: "Identity", default: true }, { name: "images", title: "Images" },
    { name: "text", title: "Text" }, { name: "display", title: "Display" }, { name: "video", title: "Video" },
    { name: "exhibition", title: "Exhibition mode" }, { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({ name: "title", type: "localizedString", group: "identity", validation: (rule) => rule.required() }),
    defineField({ name: "slug", type: "slug", group: "identity", description: "Press Generate to create the URL from the English title.", options: { source: (document) => (document.title as { en?: string } | undefined)?.en || "artwork", maxLength: 96 }, validation: (rule) => rule.required() }),
    defineField({ name: "internalId", type: "string", group: "identity", hidden: true, readOnly: true, description: "Legacy technical identifier retained for existing records." }),
    defineField({ name: "inventoryNumber", type: "string", group: "identity", hidden: true, readOnly: true, description: "Legacy inventory identifier retained for existing records." }),
    defineField({ name: "year", type: "number", group: "identity", validation: (rule) => rule.required().min(1900).max(2200) }),
    defineField({ name: "series", title: "Collection", type: "reference", to: [{ type: "series" }], group: "identity" }),
    defineField({ name: "mediumRef", title: "Material / Medium", type: "reference", to: [{ type: "material" }], group: "identity", description: "Choose one translated material. It is displayed and filtered in the current site language." }),
    defineField({ name: "medium", title: "Legacy medium", type: "string", group: "identity", hidden: true, readOnly: true, description: "Preserved until all records have been migrated to Material / Medium." }),
    defineField({ name: "materials", type: "array", of: [{ type: "string" }], group: "identity", hidden: true, readOnly: true, description: "Legacy free-text materials." }),
    defineField({ name: "category", title: "Legacy category", type: "string", group: "identity", hidden: true, readOnly: true }),
    defineField({ name: "orientation", title: "Legacy orientation", type: "string", group: "identity", hidden: true, readOnly: true, options: { list: ["portrait", "landscape", "square"] } }),
    defineField({ name: "tags", title: "Legacy tags", type: "array", of: [{ type: "string" }], group: "identity", hidden: true, readOnly: true, options: { layout: "tags" } }),
    defineField({ name: "dimensions", type: "dimensions", group: "identity" }),
    defineField({ name: "availability", type: "string", group: "identity", options: { list: ["available", "reserved", "sold", "private-collection", "museum", "unavailable"] } }),
    defineField({ name: "showPrice", title: "Show price on website", type: "boolean", group: "identity", initialValue: false }),
    defineField({ name: "prices", title: "Prices by site language", type: "object", group: "identity", hidden: ({ parent }) => !parent?.showPrice, description: "English shows USD, Russian shows RUB, Chinese shows CNY. Leave a currency empty to hide the price in that language.", fields: [
      defineField({ name: "usd", title: "English site — USD", type: "number", validation: (rule) => rule.positive() }),
      defineField({ name: "rub", title: "Russian site — RUB", type: "number", validation: (rule) => rule.positive() }),
      defineField({ name: "cny", title: "Chinese site — CNY", type: "number", validation: (rule) => rule.positive() }),
    ] }),
    defineField({ name: "price", title: "Legacy price", type: "number", group: "identity", hidden: true, readOnly: true }),
    defineField({ name: "currency", title: "Legacy currency", type: "string", group: "identity", hidden: true, readOnly: true }),
    defineField({ name: "mainImage", title: "Main Artwork Image", type: "imageWithMetadata", group: "images", description: "Required canonical image. Shown complete on the detail page, fullscreen viewer and inside View in Space.", validation: (rule) => rule.required() }),
    defineField({ name: "heroImage", title: "Legacy homepage image", type: "imageWithMetadata", group: "images", hidden: true, readOnly: true }),
    defineField({ name: "galleryImage", title: "Legacy archive image", type: "imageWithMetadata", group: "images", hidden: true, readOnly: true }),
    defineField({ name: "detailImages", title: "Detail Images", type: "array", group: "images", description: "Close-up details shown in the artwork slider and Details section. Use Upload several images for batch upload.", components: { input: BulkImageArrayInput }, of: [defineArrayMember({ type: "imageWithMetadata" })] }),
    defineField({ name: "textureImages", title: "Texture Images", type: "array", group: "images", description: "Additional texture close-ups shown after Detail Images. Use Upload several images for batch upload.", components: { input: BulkImageArrayInput }, of: [defineArrayMember({ type: "imageWithMetadata" })] }),
    defineField({ name: "interiorImages", title: "Legacy per-artwork interior images", type: "array", group: "images", hidden: true, readOnly: true, description: "Preserved for backward compatibility. View in Space now uses global Interior Scenes.", of: [defineArrayMember({ type: "imageWithMetadata" })] }),
    defineField({ name: "videoFile", title: "Video file", type: "file", group: "video", description: "Upload an H.264 MP4 or WebM file for reliable browser playback. Large files should be web-optimized.", options: { accept: "video/mp4,video/webm" } }),
    defineField({ name: "videoExternalUrl", title: "Direct video URL", type: "url", group: "video", description: "Optional direct MP4/WebM URL. YouTube page links do not work in the native player." }),
    defineField({ name: "videoPoster", title: "Video poster", type: "imageWithMetadata", group: "video", description: "Cover image for the video. A poster alone does not provide playable video." }),
    defineField({ name: "videoEyebrow", title: "Video eyebrow", type: "localizedString", group: "video" }),
    defineField({ name: "videoTitle", title: "Video title", type: "localizedString", group: "video" }),
    defineField({ name: "videoCaption", title: "Video caption", type: "localizedText", group: "video" }),
    defineField({ name: "shortDescription", type: "localizedText", group: "text" }),
    defineField({ name: "description", type: "localizedPortableText", group: "text" }),
    defineField({ name: "artistComment", type: "localizedText", group: "text" }),
    defineField({ name: "additionalText", type: "localizedPortableText", group: "text" }),
    defineField({ name: "exhibitions", type: "array", of: [defineArrayMember({ type: "reference", to: [{ type: "exhibition" }] })], group: "display" }),
    defineField({ name: "relatedArtworks", type: "array", of: [defineArrayMember({ type: "reference", to: [{ type: "artwork" }] })], group: "display" }),
    defineField({ name: "featured", type: "boolean", group: "display", initialValue: false }),
    defineField({ name: "showOnHomepage", type: "boolean", group: "display", initialValue: false }),
    defineField({ name: "homepageOrder", type: "number", group: "display" }),
    defineField({ name: "artworkOrder", type: "number", group: "display" }),
    defineField({ name: "hideFromArchive", type: "boolean", group: "display", initialValue: false }),
    defineField({ name: "viewInSpaceEnabled", type: "boolean", group: "display", initialValue: true }),
    defineField({ name: "preferredInteriorScene", type: "reference", to: [{ type: "interiorScene" }], group: "display" }),
    defineField({ name: "frameAllowed", type: "boolean", group: "display", initialValue: true }),
    defineField({ name: "trueScaleEnabled", type: "boolean", group: "display", initialValue: true }),
    defineField({ name: "exhibitionFeatured", type: "boolean", group: "exhibition", initialValue: false }),
    defineField({ name: "exhibitionOrder", type: "number", group: "exhibition" }),
    defineField({ name: "exhibitionScale", type: "number", group: "exhibition", description: "Optional gentle scale hint. Leave empty for automatic curation.", validation: (rule) => rule.min(0.75).max(1.2) }),
    defineField({ name: "exhibitionAlignment", type: "string", group: "exhibition", options: { list: ["auto", "left", "center", "right"] }, initialValue: "auto" }),
    defineField({ name: "exhibitionOffset", type: "object", group: "exhibition", description: "Optional subtle offset; automatic composition is used by default.", fields: [
      { name: "x", type: "number", validation: (rule) => rule.min(-20).max(20) },
      { name: "y", type: "number", validation: (rule) => rule.min(-20).max(20) },
    ] }),
    defineField({ name: "seo", type: "seoFields", group: "seo" }),
  ],
  preview: { select: { title: "title.en", year: "year", status: "availability", media: "mainImage" }, prepare: ({ title, year, status, media }) => ({ title: title ?? "Untitled", subtitle: [year, status].filter(Boolean).join(" · "), media }) },
});
