import { defineArrayMember, defineField, defineType } from "sanity";

export const artwork = defineType({
  name: "artwork", title: "Artwork", type: "document",
  groups: [
    { name: "identity", title: "Identity", default: true }, { name: "images", title: "Images" },
    { name: "text", title: "Text" }, { name: "display", title: "Display" }, { name: "video", title: "Video" },
    { name: "exhibition", title: "Exhibition mode" }, { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({ name: "title", type: "localizedString", group: "identity", validation: (rule) => rule.required() }),
    defineField({ name: "slug", type: "slug", group: "identity", options: { source: "internalId", maxLength: 96 }, validation: (rule) => rule.required() }),
    defineField({ name: "internalId", type: "string", group: "identity", validation: (rule) => rule.required() }),
    defineField({ name: "inventoryNumber", type: "string", group: "identity" }),
    defineField({ name: "year", type: "number", group: "identity", validation: (rule) => rule.required().min(1900).max(2200) }),
    defineField({ name: "series", title: "Collection", type: "reference", to: [{ type: "series" }], group: "identity" }),
    defineField({ name: "medium", type: "string", group: "identity" }),
    defineField({ name: "materials", type: "array", of: [{ type: "string" }], group: "identity" }),
    defineField({ name: "category", type: "string", group: "identity" }),
    defineField({ name: "orientation", type: "string", group: "identity", options: { list: ["portrait", "landscape", "square"] } }),
    defineField({ name: "tags", type: "array", of: [{ type: "string" }], group: "identity", options: { layout: "tags" } }),
    defineField({ name: "dimensions", type: "dimensions", group: "identity" }),
    defineField({ name: "availability", type: "string", group: "identity", options: { list: ["available", "reserved", "sold", "private-collection", "museum", "unavailable"] } }),
    defineField({ name: "price", type: "number", group: "identity", hidden: ({ parent }) => !parent?.showPrice }),
    defineField({ name: "currency", type: "string", group: "identity", hidden: ({ parent }) => !parent?.showPrice }),
    defineField({ name: "showPrice", type: "boolean", group: "identity", initialValue: false }),
    defineField({ name: "mainImage", type: "imageWithMetadata", group: "images", validation: (rule) => rule.required() }),
    defineField({ name: "heroImage", type: "imageWithMetadata", group: "images" }),
    defineField({ name: "galleryImage", type: "imageWithMetadata", group: "images" }),
    defineField({ name: "detailImages", type: "array", group: "images", of: [defineArrayMember({ type: "imageWithMetadata" })] }),
    defineField({ name: "textureImages", type: "array", group: "images", of: [defineArrayMember({ type: "imageWithMetadata" })] }),
    defineField({ name: "interiorImages", type: "array", group: "images", of: [defineArrayMember({ type: "imageWithMetadata" })] }),
    defineField({ name: "mobileImage", type: "imageWithMetadata", group: "images" }),
    defineField({ name: "videoFile", title: "Video file", type: "file", group: "video", options: { accept: "video/mp4,video/webm" } }),
    defineField({ name: "videoExternalUrl", title: "External video URL", type: "url", group: "video" }),
    defineField({ name: "videoPoster", title: "Video poster", type: "imageWithMetadata", group: "video" }),
    defineField({ name: "videoEyebrow", title: "Video eyebrow", type: "localizedString", group: "video" }),
    defineField({ name: "videoTitle", title: "Video title", type: "localizedString", group: "video" }),
    defineField({ name: "videoCaption", title: "Video caption", type: "localizedText", group: "video" }),
    defineField({ name: "shortDescription", type: "localizedText", group: "text" }),
    defineField({ name: "description", type: "localizedPortableText", group: "text" }),
    defineField({ name: "artistComment", type: "localizedText", group: "text" }),
    defineField({ name: "additionalText", type: "localizedPortableText", group: "text" }),
    defineField({ name: "exhibitions", type: "array", of: [defineArrayMember({ type: "reference", to: [{ type: "exhibition" }] })], group: "display" }),
    defineField({ name: "relatedArtworks", type: "array", of: [defineArrayMember({ type: "reference", to: [{ type: "artwork" }] })], group: "display" }),
    defineField({ name: "featured", type: "boolean", group: "display", initialValue: false }),
    defineField({ name: "showOnHomepage", type: "boolean", group: "display", initialValue: false }),
    defineField({ name: "homepageOrder", type: "number", group: "display" }),
    defineField({ name: "artworkOrder", type: "number", group: "display" }),
    defineField({ name: "hideFromArchive", type: "boolean", group: "display", initialValue: false }),
    defineField({ name: "viewInSpaceEnabled", type: "boolean", group: "display", initialValue: true }),
    defineField({ name: "preferredInteriorScene", type: "reference", to: [{ type: "interiorScene" }], group: "display" }),
    defineField({ name: "frameAllowed", type: "boolean", group: "display", initialValue: true }),
    defineField({ name: "trueScaleEnabled", type: "boolean", group: "display", initialValue: true }),
    defineField({ name: "exhibitionFeatured", type: "boolean", group: "exhibition", initialValue: false }),
    defineField({ name: "exhibitionOrder", type: "number", group: "exhibition" }),
    defineField({ name: "exhibitionScale", type: "number", group: "exhibition", description: "Optional gentle scale hint. Leave empty for automatic curation.", validation: (rule) => rule.min(0.75).max(1.2) }),
    defineField({ name: "exhibitionAlignment", type: "string", group: "exhibition", options: { list: ["auto", "left", "center", "right"] }, initialValue: "auto" }),
    defineField({ name: "exhibitionOffset", type: "object", group: "exhibition", description: "Optional subtle offset; automatic composition is used by default.", fields: [
      { name: "x", type: "number", validation: (rule) => rule.min(-20).max(20) },
      { name: "y", type: "number", validation: (rule) => rule.min(-20).max(20) },
    ] }),
    defineField({ name: "seo", type: "seoFields", group: "seo" }),
  ],
  preview: { select: { title: "title.0.value", year: "year", status: "availability", media: "mainImage" }, prepare: ({ title, year, status, media }) => ({ title: title ?? "Untitled", subtitle: [year, status].filter(Boolean).join(" · "), media }) },
});
